- name: Update debian packages
  hosts: 3dprinter
  tasks:
    - name: apt updates
      apt:
        name: '*'
        state: latest
        update_cache: yes
        only_upgrade: yes
      register: apt_update_status

    - name: apt autoremove
      apt:
        autoremove: yes

    - name: setup reboot after updates
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: reboot after updates
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
